include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    unnecessary_this: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
